# Generated by Django 5.2.6 on 2026-08-30 16:29

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_password_hash", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_role_9fc6ca_idx",
            old_name="accounts_us_role_1c99bd_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_departm_78e79a_idx",
            old_name="accounts_us_departm_0e9e2c_idx",
        ),
        migrations.AddField(
            model_name="passwordchangerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_password_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordchangerequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_change_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordchangerequest",
            index=models.Index(
                fields=["user", "status"], name="accounts_pa_user_id_735564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordchangerequest",
            index=models.Index(
                fields=["status", "created_at"], name="accounts_pa_status_d33e7e_idx"
            ),
        ),
    ]
