# Generated by Django 5.2.6 on 2026-08-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_pr_user_id_1c1e6a_idx_accounts_pr_user_id_348887_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="profilechangerequest",
            new_name="accounts_pr_user_id_348887_idx",
            old_name="accounts_pr_user_id_8a0e35_idx",
        ),
        migrations.RenameIndex(
            model_name="profilechangerequest",
            new_name="accounts_pr_status_a97e02_idx",
            old_name="accounts_pr_status_2e2b72_idx",
        ),
    ]
