# Generated by Django 5.2.6 on 2026-08-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notice',
            new_name='notices_not_status_4b6b62_idx',
            old_name='notices_not_status_3d1d6a_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='notices_not_priorit_5bf0dd_idx',
            old_name='notices_not_priorit_0a0a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='noticelog',
            new_name='notices_not_notice__9a9eaa_idx',
            old_name='notices_not_notice__0d6b15_idx',
        ),
        migrations.RenameIndex(
            model_name='noticelog',
            new_name='notices_not_user_id_7bba2a_idx',
            old_name='notices_not_user_id_75cf67_idx',
        ),
    ]
